### ISSUE TITLE
Resources from different origin but same protocol should load

### ISSUE THREAD

**Issue by Gozala** [mozilla/libdweb#55]
Several issue were reported that seem to prevent embedding or loading content from same protocol but a different origin:

- [x]  Document `<img src="dweb://html/dot.svg" />` does load image if loading document URL has different origin e.g. `dweb://foo/` (For details see #54) 
- [x] Document like `<video src="dweb://html/video.webm" />` does not load video if loading document URL has different origin e.g. `dweb://foo/` (For details see #57) 
- [x] Link like `<a href="dweb://async">async</a>` does not load when clicked if document URL has different origin e.g. `dweb://hello/` (For details see #62)

**Comment by Gozala** [comment]
Just tested and #69 does fix `dweb://foo/` example that embeds `<img src="dweb://html/dot.svg" />`. Will confirm video next.

**Comment by Gozala** [comment]
Also quoting issue pointed out in #62 by @willemneal  here, which is caused by the same issue

> Currently dweb links don't have an effect. I'm sure this would work by registering an on click function for each link, but I thought it would just work with <a href="dweb://async">async</a> since it works with other protocols.

**Comment by Gozala** [comment]
Verified that #69 also addresses example with embedded video.

**Comment by lidel** [comment]
Just confirmed it works as expected, thank you!
